const API_BASE_URL = import.meta.env.VITE_API_BASE_URL || '/api';

const endpoints = {
  auth: {
    login: `${API_BASE_URL}/auth/login`,
    logout: `${API_BASE_URL}/auth/logout`,
    register: `${API_BASE_URL}/auth/register`,
  },
  dashboard: {
    stats: `${API_BASE_URL}/dashboard/stats`,
    overview: `${API_BASE_URL}/dashboard/overview`,
    activeProjects: `${API_BASE_URL}/dashboard/active-projects`,
    freelancersByCountry: `${API_BASE_URL}/dashboard/freelancers-by-country`,
    projectsByField: `${API_BASE_URL}/dashboard/projects-by-field`,
  },
  skills: {
    getAll: `${API_BASE_URL}/skills`,
    getById: (id: string | number) => `${API_BASE_URL}/skills/${id}`,
    create: `${API_BASE_URL}/skills`,
    update: (id: string | number) => `${API_BASE_URL}/skills/${id}`,
    delete: (id: string | number) => `${API_BASE_URL}/skills/${id}`,
  },
  specifications: {
    getAll: `${API_BASE_URL}/specifications`,
    getById: (id: string | number) => `${API_BASE_URL}/specifications/${id}`,
    create: `${API_BASE_URL}/specifications`,
    update: (id: string | number) => `${API_BASE_URL}/specifications/${id}`,
    delete: (id: string | number) => `${API_BASE_URL}/specifications/${id}`,
  },
  tags: {
    getAll: `${API_BASE_URL}/tags`,
    getById: (id: string | number) => `${API_BASE_URL}/tags/${id}`,
    create: `${API_BASE_URL}/tags`,
    update: (id: string | number) => `${API_BASE_URL}/tags/${id}`,
    delete: (id: string | number) => `${API_BASE_URL}/tags/${id}`,
  },
  privacyPolicy: {
    getAll: `${API_BASE_URL}/privacy-policies`,
    getById: (id: string | number) => `${API_BASE_URL}/privacy-policies/${id}`,
    create: `${API_BASE_URL}/privacy-policies`,
    update: (id: string | number) => `${API_BASE_URL}/privacy-policies/${id}`,
    delete: (id: string | number) => `${API_BASE_URL}/privacy-policies/${id}`,
  },
  employees: {
    getAll: `${API_BASE_URL}/employees`,
    getById: (id: string | number) => `${API_BASE_URL}/employees/${id}`,
    create: `${API_BASE_URL}/employees`,
    update: (id: string | number) => `${API_BASE_URL}/employees/${id}`,
    delete: (id: string | number) => `${API_BASE_URL}/employees/${id}`,
    login: `${API_BASE_URL}/employees/login`,
    getMe: `${API_BASE_URL}/employees/me`,
  },
  s3: {
    getUploadUrl: `${API_BASE_URL}/s3/upload-url`,
  },
  users: {
    getAll: `${API_BASE_URL}/users`,
    getById: (id: string | number) => `${API_BASE_URL}/users/${id}`,
    verifyFreelancer: (id: string | number) => `${API_BASE_URL}/users/${id}/verify/freelancer`,
    verifyClient: (id: string | number) => `${API_BASE_URL}/users/${id}/verify/client`,
    unverifyFreelancer: (id: string | number) => `${API_BASE_URL}/users/${id}/unverify/freelancer`,
    unverifyClient: (id: string | number) => `${API_BASE_URL}/users/${id}/unverify/client`,
    getIdentity: (id: string | number) => `${API_BASE_URL}/users/${id}/identity`,
  },
  proposals: {
    getByUserId: (userId: string | number) => `${API_BASE_URL}/proposals/user/${userId}`,
    getByProjectId: (projectId: string | number) => `${API_BASE_URL}/proposals/project/${projectId}`,
  },
  contracts: {
    getById: (id: string | number) => `${API_BASE_URL}/contracts/${id}`,
    getFinancial: (id: string | number) => `${API_BASE_URL}/contracts/${id}/financial`,
    getByClientId: (clientId: string | number) => `${API_BASE_URL}/contracts/client/${clientId}`,
    getByFreelancerId: (freelancerId: string | number) => `${API_BASE_URL}/contracts/freelancer/${freelancerId}`,
    getByProjectId: (projectId: string | number) => `${API_BASE_URL}/contracts/project/${projectId}`,
    getHistory: (projectId: string | number) => `${API_BASE_URL}/contracts/project/${projectId}/history`,
    getLatest: `${API_BASE_URL}/contracts/employee/latest`,
  },
  reports: {
    list: `${API_BASE_URL}/reports`,
    getById: (id: string | number) => `${API_BASE_URL}/reports/${id}`,
    update: (id: string | number) => `${API_BASE_URL}/reports/${id}`,
  },
  withdrawals: {
    create: `${API_BASE_URL}/withdrawals`,
    getMy: `${API_BASE_URL}/withdrawals`,
    getAll: `${API_BASE_URL}/withdrawals/all`,
    updateStatus: (id: string | number) => `${API_BASE_URL}/withdrawals/${id}/status`,
  },
  wallet: {
    getAllTransactions: `${API_BASE_URL}/wallet/transactions/all`,
    getTransactions: `${API_BASE_URL}/wallet/transactions`,
    getTransactionById: (id: string | number) => `${API_BASE_URL}/wallet/transactions/${id}`,
    getTaxableTransactions: `${API_BASE_URL}/wallet/transactions/taxable`,
    topUp: `${API_BASE_URL}/wallet/top-up`,
    verifyTransaction: (id: string | number) => `${API_BASE_URL}/wallet/transactions/${id}/verify`,
    getCards: `${API_BASE_URL}/wallet/cards`,
    startContractTransaction: (contractId: string | number) => `${API_BASE_URL}/wallet/contracts/${contractId}/start-transaction`,
    verifyContractTransaction: (id: string | number) => `${API_BASE_URL}/wallet/transactions/${id}/verify-contract`,
    verifyContractTransactionCard: (id: string | number) => `${API_BASE_URL}/wallet/transactions/${id}/verify-contract-card`,
  },
  projects: {
    getAll: `${API_BASE_URL}/projects`,
    getById: (id: string | number) => `${API_BASE_URL}/projects/${id}`,
    getByUserId: (userId: string | number) => `${API_BASE_URL}/projects?createdById=${userId}`,
  },
  demands: {
    verification: {
      getAll: `${API_BASE_URL}/demands/verification`,
      getCount: `${API_BASE_URL}/demands/verification/count`,
    },
    tagAttachments: {
      getAll: `${API_BASE_URL}/demands/tag-attachments`,
      getCount: `${API_BASE_URL}/demands/tag-attachments/count`,
      updateStatus: (id: string | number) => `${API_BASE_URL}/tags/attachments/${id}/status`,
    },
    experience: {
      getAll: `${API_BASE_URL}/experience-demands`,
      getById: (id: string | number) => `${API_BASE_URL}/experience-demands/${id}`,
      getUnderReview: `${API_BASE_URL}/experience-demands/under-review`,
      getCount: `${API_BASE_URL}/experience-demands/count`,
      create: `${API_BASE_URL}/experience-demands`,
      update: (id: string | number) => `${API_BASE_URL}/experience-demands/${id}`,
      approve: (id: string | number) => `${API_BASE_URL}/experience-demands/${id}/approve`,
      reject: (id: string | number) => `${API_BASE_URL}/experience-demands/${id}/reject`,
      delete: (id: string | number) => `${API_BASE_URL}/experience-demands/${id}`,
    },
  },
  complains: {
    getAll: `${API_BASE_URL}/complains`,
    getById: (id: string | number) => `${API_BASE_URL}/complains/${id}`,
    create: `${API_BASE_URL}/complains`,
    update: (id: string | number) => `${API_BASE_URL}/complains/${id}`,
    delete: (id: string | number) => `${API_BASE_URL}/complains/${id}`,
    markAsRead: (id: string | number) => `${API_BASE_URL}/complains/${id}/read`,
    markAsUnread: (id: string | number) => `${API_BASE_URL}/complains/${id}/unread`,
    pin: (id: string | number) => `${API_BASE_URL}/complains/${id}/pin`,
    unpin: (id: string | number) => `${API_BASE_URL}/complains/${id}/unpin`,
    resolve: (id: string | number) => `${API_BASE_URL}/complains/${id}/resolve`,
    getCount: `${API_BASE_URL}/complains/count`,
  },
  chat: {
    conversations: {
      create: `${API_BASE_URL}/chat/conversations`,
      getAll: `${API_BASE_URL}/chat/conversations`,
      getById: (id: string) => `${API_BASE_URL}/chat/conversations/${id}`,
      delete: (id: string) => `${API_BASE_URL}/chat/conversations/${id}`,
      markAsRead: (id: string) => `${API_BASE_URL}/chat/conversations/${id}/read`,
    },
    messages: {
      send: (conversationId: string) => `${API_BASE_URL}/chat/conversations/${conversationId}/messages`,
      getByConversation: (conversationId: string) => `${API_BASE_URL}/chat/conversations/${conversationId}/messages`,
      getById: (id: string) => `${API_BASE_URL}/chat/messages/${id}`,
      update: (id: string) => `${API_BASE_URL}/chat/messages/${id}`,
      delete: (id: string) => `${API_BASE_URL}/chat/messages/${id}`,
    },
  },
  push: {
    register: `${API_BASE_URL}/push/register`,
    revoke: `${API_BASE_URL}/push/revoke`,
    test: `${API_BASE_URL}/push/test`,
    notify: `${API_BASE_URL}/push/notify`,
    broadcast: `${API_BASE_URL}/push/broadcast`,
  },
};

export default endpoints;
export { endpoints as endPoints };